# Generated by Django 3.2.7 on 2021-09-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='view',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
